FlexDeploy 8.0.0.3/fdtlt88/SalesSummary-Project/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Summary_Month__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Summary Month</label>
        <referenceTo>Summary__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlexDeploy 8.0.0.3/fdtlt88/SalesSummary-Project/objects/Summary__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Summary</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlexDeploy 8.0.0.3/fdtlt88/SalesSummary-Project/classes/InvoiceController.cls
public class InvoiceController {
	public static void SummaryMonthSelection(List<Invoice__c> invList, Map<ID, Invoice__c> oldMap)
    {
        Date invoiceDate;
        Boolean dateChange = FALSE;
        for(Invoice__c inv:invList)
        {
            if(inv.Invoice_Date__c != NULL && oldMap == NULL)
            {
                invoiceDate = inv.Invoice_Date__c;
                dateChange = TRUE;
            }
            else if(inv.Invoice_Date__c != NULL & inv.Invoice_Date__c != oldMap.get(inv.Id).Invoice_Date__c)
            {
                invoiceDate = inv.Invoice_Date__c;
                dateChange = TRUE;
            }
        }
        
        if(dateChange == TRUE)
        {
            List<ID> sumID = New List<ID>();
            
            List<Summary__c> summaryList = [SELECT ID, Start_Date__c, End_Date__c FROM Summary__c];
            for(Summary__c sum:summaryList)
            {
                if(invoiceDate >= sum.Start_Date__c && invoiceDate <= sum.End_Date__c)
                {
                    sumID.add(sum.Id);
                    BREAK;
                }
            }
            
            for(Invoice__c inv:invList)
            {
                if(sumID.size()>0)
                {
                    inv.Summary_Month__c = sumID[0];
                }
                else
                {
                    inv.Summary_Month__c.addError('Month Not Found');
                }
            }
        }
    }
}